In [6]:
import tensorflow as tf

In [7]:
hello=tf.constant("Hello World")

In [8]:
sess=tf.Session()

In [9]:
print(sess.run(hello))

b'Hello World'


In [12]:
print (tf.__version__)

1.5.0


In [13]:
a=tf.constant(10)

In [14]:
b=tf.constant(15)

In [17]:
with tf.Session() as sess:
    print(sess.run(a+b))

25


In [20]:
sess=tf.InteractiveSession()
myzeros=tf.zeros((4,4))
myones=tf.ones((4,4))
myrandn=tf.random_normal((4,4),mean=0,stddev=1.0)
myrandu=tf.random_uniform((4,4),minval=0,maxval=1)
ops=[myzeros,myones,myrandn,myrandu]
for op in ops:
    print(sess.run(op))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.8520881  -0.8151385   0.8268216   0.07511695]
 [-0.9352491   1.1766447  -0.07319631  0.76556563]
 [ 0.0144012   0.4960252   0.43380353 -2.0210717 ]
 [-3.1222458   0.5439422   0.51657313  0.28067818]]
[[0.8260422  0.20413911 0.3199792  0.80332077]
 [0.9199194  0.18441689 0.5586331  0.3019712 ]
 [0.4728105  0.26659334 0.52151215 0.49300885]
 [0.92228055 0.25927293 0.06683576 0.6604208 ]]
